SLACK_CONTACT_CHANNEL_ID = 'C068UMGLCDQ'
SLACK_REMIND_CHANNEL_ID = 'C06PLQBFEU9'
SLACK_GLOBAL_SEEDING_CHANNEL_ID = 'C06803FHVUP'
SLACK_GLOBAL_EQB_CHANNEL_ID = 'C07MBEB45SQ'
MSG_TYPE = {
    'BLOCK': 'block',
    'TEXT': 'text'
}