SLACK_CONTACT_CHANNEL_ID = 'C068UMGLCDQ'
SLACK_REMIND_CHANNEL_ID = 'C06PLQBFEU9'
SLACK_GLOBAL_SEEDING_CHANNEL_ID = 'C06803FHVUP'
SLACK_GLOBAL_EQB_CHANNEL_ID = 'C07MBEB45SQ'
SLACK_GLOBAL_B2B_INVOICE_ID = {
    'EQB': 'C089MQZS0MT',
    'BRDN': 'C08LF0LFCKU'
}
SLACK_GLOBAL_B2B_DELIVERY_REQUEST_ID = 'C072F0S4LNB'
MSG_TYPE = {
    'BLOCK': 'block',
    'TEXT': 'text'
}